---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-free5gc-smf
  namespace: project-flux
spec:
  chart:
    spec:
      chart: free5gc-smf
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: source-project-flux
  interval: 24h0m0s
  
