---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-free5gc-smf
  namespace: project-flux
spec:
  chart:
    spec:
      chart: free5gc-smf
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: source-project-flux
  interval: 24h0m0s
  values:
    global:
      userPlaneArchitecture: ulcl
    smf:
      configuration:
        configuration: "smfName: SMF\nserviceNameList:\n  - nsmf-pdusession\n  - nsmf-event-exposure\n
          \ - nsmf-oam\nsnssaiInfos:\n  - sNssai:\n      sst: 1\n      sd: 010203\n
          \   dnnInfos: # DNN information list\n      - dnn: internet # Data Network
          Name\n        dns: # the IP address of DNS\n          ipv4: 8.8.8.8\n          ipv6:
          2001:4860:4860::8888\n  - sNssai:\n      sst: 1\n      sd: 112233\n    dnnInfos:
          # DNN information list\n      - dnn: internet # Data Network Name\n        dns:
          # the IP address of DNS\n          ipv4: 8.8.8.8\n          ipv6: 2001:4860:4860::8888\n
          \ - sNssai:\n      sst: 2\n      sd: 112234    \n    dnnInfos:\n      -
          dnn: internet\n        dns: \n          ipv4: 8.8.8.8\n          ipv6: 2001:4860:4860::8888\nplmnList:
          # the list of PLMN IDs that this SMF belongs to (optional, remove this key
          when unnecessary)\n  - mcc: \"208\" # Mobile Country Code (3 digits string,
          digit: 0~9)\n    mnc: \"93\" # Mobile Network Code (2 or 3 digits string,
          digit: 0~9)\nuserplane_information: # list of userplane information\n  up_nodes:
          # information of userplane node (AN or UPF)\n    gNB1: # the name of the
          node\n      type: AN # the type of the node (AN or UPF)\n    BranchingUPF:\n
          \     type: UPF\n      node_id: 10.100.50.241 # PFCP address\n      sNssaiUpfInfos:\n
          \       - sNssai:\n            sst: 1\n            sd: 010203\n          dnnUpfInfoList:\n
          \           - dnn: internet\n        - sNssai:\n            sst: 1\n            sd:
          112233\n          dnnUpfInfoList:\n            - dnn: internet\n      interfaces:\n
          \       - interfaceType: N3\n          endpoints:\n            - 10.100.50.233\n
          \         networkInstance: internet\n        - interfaceType: N9\n          endpoints:\n
          \           - 10.100.50.225\n          networkInstance: internet\n    AnchorUPF1:\n
          \     type: UPF\n      node_id: 10.100.50.242 # PFCP address\n      sNssaiUpfInfos:\n
          \       - sNssai:\n            sst: 1\n            sd: 010203\n          dnnUpfInfoList:\n
          \           - dnn: internet\n              pools:\n              - cidr:
          10.1.0.0/17\n      interfaces:\n        - interfaceType: N9\n          endpoints:\n
          \           - 10.100.50.226 # AnchorUPF1 N9 address\n          networkInstance:
          internet\n    AnchorUPF2:\n      type: UPF\n      node_id: 10.100.50.243
          # PFCP address\n      sNssaiUpfInfos:\n        - sNssai:\n            sst:
          1\n            sd: 010203\n          dnnUpfInfoList:\n            - dnn:
          internet\n              pools:\n              - cidr: 10.1.128.0/17\n      interfaces:\n
          \       - interfaceType: N9\n          endpoints:\n            - 10.100.50.227
          # AnchorUPF2 N9 address\n          networkInstance: internet\n  links:\n
          \   - A: gNB1\n      B: BranchingUPF\n    - A: BranchingUPF\n      B: AnchorUPF1\n
          \   - A: BranchingUPF\n      B: AnchorUPF2\nlocality: area1 # Name of the
          location where a set of AMF, SMF and UPFs are located\nulcl: true"

