---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-free5gc-smf
  namespace: project-flux
spec:
  chart:
    spec:
      chart: free5gc-smf
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: source-project-flux
  interval: 24h0m0s
  values:
    fullnameOverride: ""
    global:
      n4network:
        cidr: 29
        excludeIP: 10.100.50.246
        gatewayIP: 10.100.50.246
        masterIf: eth0
        name: n4network
        subnetIP: 10.100.50.240
      nrf:
        service:
          name: nrf-nnrf
          nodePort: "30800"
          port: "8000"
          type: ClusterIP
      projectName: free5gc
      sbi:
        scheme: http
      smf:
        n4if:
          ipAddress: 10.100.50.244
      userPlaneArchitecture: single
    initcontainers:
      busybox:
        image: busybox
        tag: 1.32.0
      curl:
        image: initcurl
        registry: towards5gs
        tag: 1.0.0
    mongodb:
      service:
        name: mongodb
        nodePort: "30017"
        port: 27017
        type: ClusterIP
    nameOverride: ""
    smf:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: smf-configmap
      configuration:
        configuration: ""
        logger:
          Aper:
            ReportCaller: false
            debugLevel: info
          NAS:
            ReportCaller: false
            debugLevel: info
          NGAP:
            ReportCaller: false
            debugLevel: info
          OpenApi:
            ReportCaller: false
            debugLevel: info
          PFCP:
            ReportCaller: false
            debugLevel: info
          PathUtil:
            ReportCaller: false
            debugLevel: info
          SMF:
            ReportCaller: false
            debugLevel: info
        ueRoutingInfo: |-
          UE1: # Group Name
            members:
            - imsi-208930000000003 # Subscription Permanent Identifier of the UE
            topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
            # default path derived from this topology
            # node name should be consistent with smfcfg.yaml
              - A: gNB1
                B: BranchingUPF
              - A: BranchingUPF
                B: AnchorUPF1
            specificPath:
              - dest: 10.100.100.26/32 # the destination IP address on Data Network (DN)
                # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
                # The UPF's name should be consistent with smfcfg.yaml
                path: [BranchingUPF, AnchorUPF2]

          UE2: # Group Name
            members:
            - imsi-208930000000004 # Subscription Permanent Identifier of the UE
            topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
            # default path derived from this topology
            # node name should be consistent with smfcfg.yaml
              - A: gNB1
                B: BranchingUPF
              - A: BranchingUPF
                B: AnchorUPF1
            specificPath:
              - dest: 10.100.100.16/32 # the destination IP address on Data Network (DN)
                # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
                # The UPF's name should be consistent with smfcfg.yaml
                path: [BranchingUPF, AnchorUPF2]
      image:
        name: towards5gs/free5gc-smf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        tls: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: smf
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext: {}
      service:
        name: smf-nsmf
        port: 80
        type: ClusterIP
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: smf-volume

